API_TITLE = "F1 calendar API"
LOG_LEVEL = "INFO"

OPENF1_SESSIONS_URL = "https://api.openf1.org/v1/sessions"
TARGET_YEAR = 2026
CACHE_TTL_SECONDS = 15 * 60

CORS_ALLOW_ORIGINS = ["*"]
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_METHODS = ["*"]
CORS_ALLOW_HEADERS = ["*"]
